"""Order Creator Mechanism (OCM) - Cosmic Scale Invariance & Macro-Structures.

Models the OCM scaling constant zeta_OCM ~ 612, macro-structure resonant limits L_max ~ 10.4 Gly,
annular resonance seeding frequencies f_OCM, and geometric depletion void dynamics.
"""

import numpy as np

# Physical Constants
G = 6.67430e-11  # m^3 kg^-1 s^-2
C = 2.99792458e8  # m/s
PLANCK_LENGTH = 1.616255e-35  # m
PLANCK_TIME = 5.391247e-44  # s
LY_TO_METER = 9.4607304725808e15  # m

# Cosmological Parameters
R_OBS = 4.4e26  # m (~ 46.5 Gly observable radius)
T_UNIV_SEC = 13.8e9 * 365.25 * 86400.0  # ~ 13.8 billion years in seconds


def calculate_ocm_scaling_constant(
    r_obs: float = R_OBS, l_p: float = PLANCK_LENGTH
) -> float:
    """Computes logarithmic scaling constant zeta_OCM = ln(V_horizon / V_P) = 3 * ln(R_obs / l_p)."""
    if r_obs <= 0 or l_p <= 0:
        raise ValueError("Volumes/lengths must be strictly positive.")

    # Volume ratio simplifies to 3 * ln(R_obs / l_p)
    return float(3.0 * np.log(r_obs / l_p))


def calculate_horizon_scale_limit(
    t_univ_sec: float = T_UNIV_SEC, zeta_ocm: float = 612.0
) -> float:
    """Computes theoretical maximum structural limit L_max = (c * t_univ) / zeta_ocm in light-years."""
    if t_univ_sec <= 0 or zeta_ocm <= 0:
        raise ValueError("Time and scaling constant must be strictly positive.")

    l_max_meters = (C * t_univ_sec) / zeta_ocm
    return float(l_max_meters / LY_TO_METER)


def classify_macro_structure(scale_gly: float) -> str:
    """Classifies cosmic structures based on OCM harmonic scale length (in Gly)."""
    if scale_gly < 0.1:
        return "Micro/Meso Scale: Localized Horizon Accretion Node"
    elif 1.0 <= scale_gly <= 3.5:
        return "Macro Scale: Annular Resonance / Interference Fringe (Big Ring / Giant Arc)"
    elif 3.5 < scale_gly <= 10.5:
        return "Universal Limit: Global Nodal Sheet / Connectivity Stitch (Her-CrB Wall)"
    else:
        return "Super-Horizon Limit: Non-Causal Boundary (> L_max)"


def calculate_depletion_void_radius(mass_kg: float, kappa_flux_factor: float = 1.0) -> float:
    """Estimates mechanical sweep depletion void radius generated by an active UMBH node."""
    if mass_kg <= 0:
        raise ValueError("Mass must be positive.")
    rg = (G * mass_kg) / (C**2)
    # Sweep radius scales with Rd (3 * rg) and kappa-flux pressure projection
    return 3.0 * rg * 10.0 * kappa_flux_factor
